main:
  project_name: usa_census
  experiment_name: development
  steps: all
etl:
  sample: "census.csv"
modeling:
  # Fraction of data to use for test (the remaining will be used for train and validation)
  test_size: 0.2
  # Fraction of remaining data to use for validation
  val_size: 0.2
  # Fix this for reproducibility, change to have new splits
  random_seed: 42
  # Column to use for stratification (use "none" for no stratification)
  stratify_by: "none"
  # Maximum number of features to consider for the TFIDF applied to the title of the
  # insertion (the column called "name")
  max_tfidf_features: 5
  # NOTE: you can put here any parameter that is accepted by the constructor of
  # RandomForestRegressor. This is a subsample, but more could be added:
  gradient_boosting_classifier:
    n_estimators: 100
    max_depth: 3
    min_samples_split: 2
    min_samples_leaf: 1
    criterion: friedman_mse
    max_features: 0.5
