wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.5
    session_history: code/_session_history.ipynb
    start_time: 1657662234
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      4: 3.10.5
      5: 0.12.19
      8:
      - 1
      - 5
