name: api_creation
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.3
  - pip=22.1.2
  - mlflow=1.27.0
  - scikit-learn=1.1.1
  - matplotlib=3.5.2
  - pydantic=1.9.1
  - fastapi=0.78.0
  - gunicorn=20.1.0
  - pip:
      - wandb==0.12.19
      - pillow==9.2.0
      - uvicorn==0.18.2