name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.4.3
  - requests=2.28.1
  - pip=22.1.2
  - mlflow=1.27.0
  - scikit-learn=1.1.1
  - pip:
      - wandb==0.12.19