wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.19
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1657183859
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      4: 3.10.5
      5: 0.12.19
      8:
      - 5
criterion:
  desc: null
  value: friedman_mse
gbc_config:
  desc: null
  value: /home/imdadul/Project Folder/Deploying a Machine Learning Model on Heroku
    with FastAPI/outputs/2022-07-07/09-50-56/gbc_config.json
max_depth:
  desc: null
  value: 3
max_features:
  desc: null
  value: 0.5
min_samples_leaf:
  desc: null
  value: 1
min_samples_split:
  desc: null
  value: 2
n_estimators:
  desc: null
  value: 100
output_artifact:
  desc: null
  value: gradient_boosting_export
random_seed:
  desc: null
  value: 42
stratify_by:
  desc: null
  value: none
trainval_artifact:
  desc: null
  value: trainval_data.csv:latest
val_size:
  desc: null
  value: 0.2
